### ISSUE TITLE
A security vulnerability submission

### ISSUE THREAD

**Issue by Al1ex** [mttcoin/MTTcoin-core#1]
Hello, I found a vulnerability. I want to know how to submit vulnerability details and vulnerability reward rules. You can contact me via TG(@RedTeamPing).

**Comment by mttcoin** [comment]
Hello, please email info@mttcoin.com for vulnerability reports.

**Comment by Al1ex** [comment]
okay.

**Comment by mttcoin** [comment]
Vulnerability acknowledged and rewarded.

**Comment by Al1ex** [comment]
Thank you very much.
